export * from './about';
export * from './catalog-item';
export * from './contacts';
export * from './footer';
export * from './header';
export * from './home';
export * from './not-found';
export * from './privacy-policy';
export * from './product-item';
